version: "3"

tasks:
  build:templ:
    cmds:
      - go tool templ generate
    sources:
      - "**/*.templ"
    generates:
      - "**/*_templ.go"

  build:
    deps:
      - build:templ
    cmds:
      - go build -tags=prod -o bin/main ./

  start:templ:
    cmds:
      - go tool templ generate -watch

  start:server:
    cmds:
      - |
        go tool air \
          -build.cmd "go build -tags=dev -o tmp/bin/main ./" \
          -build.bin "tmp/bin/main" \
          -build.include_ext "go,templ" \
          -misc.clean_on_exit "true"

  start:
    deps:
      - start:templ
      - start:server

  run:
    deps:
      - build
    cmds:
      - ./bin/main

  default:
    cmds:
      - task: start
