// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package slides

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

/*
Slide: Next.js directory structure (src/)

Intent:
- Show the “endless folders” feeling with a static tree of the src/ directory.
- Present it with an IDE-ish vibe: scrollable editor panel, smaller font, monospace.

Design:
- h1 is simply: "src/"
- The tree is static (paste-in).
- Scroll both directions (vertical + horizontal).

Implementation detail:
- The tree is stored in a raw string literal and rendered via { tree } to preserve newlines.
*/

func NextJSSrcTree(isPresenter bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		tree := `├── app
│   ├── (auth)
│   │   ├── forgot-password
│   │   │   ├── components
│   │   │   │   ├── ForgotPassword.tsx
│   │   │   │   └── ui
│   │   │   │       └── ForgotPasswordButton.tsx
│   │   │   ├── error.tsx
│   │   │   ├── lib
│   │   │   │   └── actions.ts
│   │   │   └── page.tsx
│   │   ├── layout.tsx
│   │   ├── login
│   │   │   ├── components
│   │   │   │   ├── LoginPage.tsx
│   │   │   │   └── ui
│   │   │   │       ├── GoogleButton.tsx
│   │   │   │       ├── LoginButton.tsx
│   │   │   │       └── PasswordTextField.tsx
│   │   │   ├── error.tsx
│   │   │   ├── lib
│   │   │   │   └── actions.ts
│   │   │   └── page.tsx
│   │   ├── logout
│   │   │   ├── components
│   │   │   │   └── LogOut.tsx
│   │   │   └── page.tsx
│   │   ├── register
│   │   │   ├── components
│   │   │   │   └── RegisterPage.tsx
│   │   │   ├── error.tsx
│   │   │   ├── lib
│   │   │   │   └── actions.ts
│   │   │   └── page.tsx
│   │   └── shared
│   │       ├── EmailTextField.tsx
│   │       └── utils.ts
│   ├── (authorized)
│   │   ├── admin
│   │   │   ├── dashboard
│   │   │   │   ├── components
│   │   │   │   │   ├── Events.tsx
│   │   │   │   │   └── FormSubmissions.tsx
│   │   │   │   ├── events
│   │   │   │   │   ├── event-dashboard
│   │   │   │   │   │   └── [id]
│   │   │   │   │   │       └── [tab]
│   │   │   │   │   │           ├── components
│   │   │   │   │   │           │   ├── EventDashboardTabs.tsx
│   │   │   │   │   │           │   └── ui
│   │   │   │   │   │           │       └── HideLabel.tsx
│   │   │   │   │   │           ├── edit
│   │   │   │   │   │           │   ├── components
│   │   │   │   │   │           │   │   └── DescriptionDialog.tsx
│   │   │   │   │   │           │   └── Edit.tsx
│   │   │   │   │   │           ├── interest
│   │   │   │   │   │           │   ├── components
│   │   │   │   │   │           │   │   ├── lib
│   │   │   │   │   │           │   │   │   └── helpers
│   │   │   │   │   │           │   │   │       └── InterestHelper.ts
│   │   │   │   │   │           │   │   └── PoolInterestLeve.tsx
│   │   │   │   │   │           │   └── InterestPage.tsx
│   │   │   │   │   │           ├── layout.tsx
│   │   │   │   │   │           ├── lib
│   │   │   │   │   │           │   ├── helpers.ts
│   │   │   │   │   │           │   └── types
│   │   │   │   │   │           │       └── types.ts
│   │   │   │   │   │           ├── loading.tsx
│   │   │   │   │   │           ├── page.tsx
│   │   │   │   │   │           ├── players
│   │   │   │   │   │           │   ├── components
│   │   │   │   │   │           │   │   ├── components
│   │   │   │   │   │           │   │   │   ├── AssignedPlayers.tsx
│   │   │   │   │   │           │   │   │   ├── components
│   │   │   │   │   │           │   │   │   │   └── PreviousGamesPlayed.tsx
│   │   │   │   │   │           │   │   │   ├── lib
│   │   │   │   │   │           │   │   │   │   ├── actions.ts
│   │   │   │   │   │           │   │   │   │   └── playerInPoolHelper.ts
│   │   │   │   │   │           │   │   │   ├── manuallyAssignPlayer.tsx
│   │   │   │   │   │           │   │   │   ├── PlayerInterestInfo.tsx
│   │   │   │   │   │           │   │   │   └── ui
│   │   │   │   │   │           │   │   │       └── AssignPlayerButtons.tsx
│   │   │   │   │   │           │   │   ├── lib
│   │   │   │   │   │           │   │   │   └── actions.ts
│   │   │   │   │   │           │   │   └── PlayerManagement.tsx
│   │   │   │   │   │           │   ├── Players.tsx
│   │   │   │   │   │           │   └── ui
│   │   │   │   │   │           │       └── PoolNameTabs.tsx
│   │   │   │   │   │           ├── room
│   │   │   │   │   │           │   └── Room.tsx
│   │   │   │   │   │           └── settings
│   │   │   │   │   │               ├── components
│   │   │   │   │   │               │   ├── lib
│   │   │   │   │   │               │   │   └── actions.ts
│   │   │   │   │   │               │   └── Ordering.tsx
│   │   │   │   │   │               └── Settings.tsx
│   │   │   │   │   ├── loading.tsx
│   │   │   │   │   └── page.tsx
│   │   │   │   ├── form-submissions
│   │   │   │   │   ├── components
│   │   │   │   │   │   └── FormSubmissionTable.tsx
│   │   │   │   │   ├── error.tsx
│   │   │   │   │   ├── hooks
│   │   │   │   │   │   ├── useColumns.tsx
│   │   │   │   │   │   └── useRealtimeTableData.tsx
│   │   │   │   │   ├── lib
│   │   │   │   │   │   ├── actions.ts
│   │   │   │   │   │   └── types.ts
│   │   │   │   │   ├── page.tsx
│   │   │   │   │   └── preview
│   │   │   │   │       └── [id]
│   │   │   │   │           └── [userid]
│   │   │   │   │               ├── error.tsx
│   │   │   │   │               ├── lib
│   │   │   │   │               │   └── actions.ts
│   │   │   │   │               └── page.tsx
│   │   │   │   ├── page.tsx
│   │   │   │   ├── participants
│   │   │   │   │   ├── add
│   │   │   │   │   │   ├── components
│   │   │   │   │   │   │   ├── TicketCard.tsx
│   │   │   │   │   │   │   └── TicketList.tsx
│   │   │   │   │   │   └── page.tsx
│   │   │   │   │   ├── components
│   │   │   │   │   │   ├── ParticipantCard.tsx
│   │   │   │   │   │   └── ParticipantsList.tsx
│   │   │   │   │   └── page.tsx
│   │   │   │   └── rooms
│   │   │   │       ├── components
│   │   │   │       │   ├── components
│   │   │   │       │   │   ├── components
│   │   │   │       │   │   │   └── RoomAddButton.tsx
│   │   │   │       │   │   ├── lib
│   │   │   │       │   │   │   └── actions.ts
│   │   │   │       │   │   ├── RoomMapItem.tsx
│   │   │   │       │   │   └── ui
│   │   │   │       │   │       ├── RoomCard.tsx
│   │   │   │       │   │       ├── RoomPoolInfo.tsx
│   │   │   │       │   │       ├── RoomSelectDialog.tsx
│   │   │   │       │   │       └── UnwantedPoolByGm.tsx
│   │   │   │       │   ├── lib
│   │   │   │       │   │   └── helpers.ts
│   │   │   │       │   └── RoomMap.tsx
│   │   │   │       └── page.tsx
│   │   │   ├── layout.tsx
│   │   │   └── page.tsx
│   │   ├── components
│   │   │   ├── BackButton.tsx
│   │   │   └── LogOutButton.tsx
│   │   ├── dashboard
│   │   │   ├── components
│   │   │   │   ├── CardBase.tsx
│   │   │   │   ├── MyEvents.tsx
│   │   │   │   └── MyTickets.tsx
│   │   │   ├── loading.tsx
│   │   │   └── page.tsx
│   │   ├── event
│   │   │   └── create
│   │   │       └── [id]
│   │   │           ├── components
│   │   │           │   ├── EventFormSkeleton.tsx
│   │   │           │   └── EventForm.tsx
│   │   │           ├── loading.tsx
│   │   │           └── page.tsx
│   │   ├── layout.tsx
│   │   ├── my-events
│   │   │   ├── components
│   │   │   │   ├── AddEventCard.tsx
│   │   │   │   ├── DynamicLink.tsx
│   │   │   │   └── RealtimeMyEvents.tsx
│   │   │   ├── error.tsx
│   │   │   ├── lib
│   │   │   │   ├── actions.ts
│   │   │   │   └── types.ts
│   │   │   ├── loading.tsx
│   │   │   └── page.tsx
│   │   └── my-profile
│   │       ├── my-tickets
│   │       │   ├── components
│   │       │   │   ├── lib
│   │       │   │   │   └── actions
│   │       │   │   │       ├── actions.ts
│   │       │   │   │       ├── AssignUserToParticipant.test.ts
│   │       │   │   │       ├── Helpers.ts
│   │       │   │   │       └── NewTickets.test.ts
│   │       │   │   ├── MyParticipantsHeader.tsx
│   │       │   │   ├── MyParticipants.tsx
│   │       │   │   └── UI
│   │       │   │       └── MyParticipantCard.tsx
│   │       │   ├── confirm
│   │       │   │   ├── components
│   │       │   │   │   └── ui
│   │       │   │   │       └── ConfirmEmailButtons.tsx
│   │       │   │   └── page.tsx
│   │       │   ├── not-found
│   │       │   │   └── page.tsx
│   │       │   ├── page.tsx
│   │       │   └── shared
│   │       │       └── ui
│   │       │           └── BuyTicketButton.tsx
│   │       └── page.tsx
│   ├── components
│   │   ├── mainAppBar.tsx
│   │   ├── SetCookie.tsx
│   │   └── ui
│   │       ├── MainAppBarContent.tsx
│   │       ├── mainAppBarDesktop.tsx
│   │       └── mainAppBarMobile.tsx
│   ├── favicon.ico
│   ├── global.scss
│   ├── layout.tsx
│   ├── page.module.scss
│   └── (public)
│       ├── assigned
│       │   ├── components
│       │   │   ├── AssignedGame.tsx
│       │   │   ├── lib
│       │   │   │   └── helper.ts
│       │   │   └── ui
│       │   │       └── LoadingAssignedGameWrapper.tsx
│       │   └── page.tsx
│       ├── components
│       │   ├── components
│       │   │   ├── EventCardBig.tsx
│       │   │   ├── EventCardSmall.tsx
│       │   │   ├── EventListWrapper.tsx
│       │   │   ├── Events.tsx
│       │   │   ├── TrashButton.tsx
│       │   │   └── ui
│       │   │       ├── EventListDay.tsx
│       │   │       └── Filter.tsx
│       │   ├── EventList.tsx
│       │   ├── lib
│       │   │   ├── helpers
│       │   │   │   ├── icons.tsx
│       │   │   │   ├── translation.ts
│       │   │   │   └── types
│       │   │   │       └── types.ts
│       │   │   ├── hooks
│       │   │   │   ├── useFilteredPoolEvents.ts
│       │   │   │   ├── useIntersectionObserver.tsx
│       │   │   │   ├── useObserveIntersectionObserver.tsx
│       │   │   │   └── useSafeRouterReplace.tsx
│       │   │   └── serverAction.ts
│       │   ├── RealtimeEvents.tsx
│       │   └── ui
│       │       ├── DaysHeader.tsx
│       │       └── Logo.tsx
│       ├── event
│       │   └── [id]
│       │       ├── components
│       │       │   ├── components
│       │       │   │   ├── InterestSelector.tsx
│       │       │   │   └── RealtimePoolEvent.tsx
│       │       │   ├── helpers
│       │       │   │   └── CustomEventListener.tsx
│       │       │   ├── MainEventBig.tsx
│       │       │   ├── MainEvent.tsx
│       │       │   └── ui
│       │       │       ├── BigMediaQueryWrapper.tsx
│       │       │       ├── ChipCarousel.tsx
│       │       │       ├── GoToEventAdministrationButton.tsx
│       │       │       ├── MuiMarkdownClient.tsx
│       │       │       ├── NavigateNextLink.tsx
│       │       │       ├── NavigatePreviousLink.tsx
│       │       │       └── SmallMediaQueryWrapper.tsx
│       │       └── page.tsx
│       ├── hjelppaamelding
│       │   └── page.tsx
│       ├── interests
│       │   ├── components
│       │   │   ├── Favorites.tsx
│       │   │   ├── lib
│       │   │   │   └── helpers
│       │   │   │       └── helpers.ts
│       │   │   └── ui
│       │   │       └── LoadingParticipantWrapper.tsx
│       │   └── page.tsx
│       ├── layout.tsx
│       └── page.tsx
├── lib
│   ├── components
│   │   ├── icons
│   │   │   ├── AdultsOnlyIcon.tsx
│   │   │   ├── BeginnerIcon.tsx
│   │   │   ├── BoardGameIcon.tsx
│   │   │   ├── CardGameIcon.tsx
│   │   │   ├── ChildFriendlyIcon.tsx
│   │   │   ├── EnglishIcon.tsx
│   │   │   ├── GameMasterIcon.tsx
│   │   │   ├── LessHoursIcon.tsx
│   │   │   ├── MiscGameIcon.tsx
│   │   │   ├── MoreHoursIcon.tsx
│   │   │   ├── RoleplayingGameIcon.tsx
│   │   │   └── SvgWrapper.tsx
│   │   └── RealtimePoolEvents.tsx
│   ├── debounce.ts
│   ├── d.ts
│   │   └── firebase-auth.d.ts
│   ├── enums.ts
│   ├── firebase
│   │   ├── config.ts
│   │   ├── firebaseAdmin.ts
│   │   └── firebase.ts
│   ├── hooks
│   │   ├── useEventListner.tsx
│   │   ├── useIsomorphicLayoutEffect.tsx
│   │   ├── useLocalStorage.tsx
│   │   ├── useReadLocalStorage.tsx
│   │   ├── useSetCustomCssVariable.tsx
│   │   └── useUser.tsx
│   ├── image
│   │   └── rook.svg
│   ├── libClient.ts
│   ├── libServer.ts
│   ├── muiTheme.ts
│   ├── serverActions
│   │   └── Migration.ts
│   └── types.ts
├── tree.txt
└── ui
    ├── ErrorBoundary
    │   ├── LoginErrorBoundary.tsx
    │   └── types.ts
    ├── participant
    │   ├── Over18.tsx
    │   ├── ParticipantAvatar.tsx
    │   └── ParticipantSelector.tsx
    └── RegnconLogo2024.tsx`
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"slide\" style=\"display:flex; flex-direction:column; gap:1.5rem;\"><h1 style=\"margin:0;\">src/</h1><div style=\"\n\t\t\t\tflex:1;\n\t\t\t\tborder-radius:16px;\n\t\t\t\tborder:1px solid rgba(255,255,255,0.14);\n\t\t\t\tbackground: rgba(0,0,0,0.45);\n\t\t\t\tbox-shadow: 0 12px 30px rgba(0,0,0,0.35);\n\t\t\t\toverflow:hidden;\n\t\t\t\"><div style=\"\n\t\t\t\t\tdisplay:flex;\n\t\t\t\t\talign-items:center;\n\t\t\t\t\tgap:0.75rem;\n\t\t\t\t\tpadding:0.75rem 1rem;\n\t\t\t\t\tborder-bottom:1px solid rgba(255,255,255,0.10);\n\t\t\t\t\tbackground: rgba(255,255,255,0.04);\n\t\t\t\t\tfont-weight:700;\n\t\t\t\t\"><div style=\"display:flex; gap:0.4rem;\"><div style=\"width:10px; height:10px; border-radius:999px; background: rgba(255,255,255,0.18);\"></div><div style=\"width:10px; height:10px; border-radius:999px; background: rgba(255,255,255,0.18);\"></div><div style=\"width:10px; height:10px; border-radius:999px; background: rgba(255,255,255,0.18);\"></div></div><div style=\"opacity:0.9;\">tree.txt</div><div style=\"margin-left:auto; opacity:0.65; font-weight:600;\">scroll ↕ ↔</div></div><div style=\"height: calc(100% - 54px); padding: 1rem;\"><pre style=\"\n\t\t\t\t\t\tmargin:0;\n\t\t\t\t\t\theight:100%;\n\t\t\t\t\t\toverflow:auto;\n\t\t\t\t\t\twhite-space:pre;\n\t\t\t\t\t\tfont-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;\n\t\t\t\t\t\tfont-size:0.95rem;\n\t\t\t\t\t\tline-height:1.25;\n\t\t\t\t\t\tcolor: rgba(255,255,255,0.92);\n\t\t\t\t\t\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(tree)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `slides/slide_next_js_src_tree.templ`, Line: 394, Col: 11}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</pre></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isPresenter {
			templ_7745c5c3_Err = nextJSSrcTreePresenterNotes().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

func nextJSSrcTreePresenterNotes() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"presenter-notes\"><ul><li>This is a static snapshot of the Next.js project’s <strong>src/</strong> folder.</li><li>The point isn’t “many files is bad” — it’s the feeling of deep nesting and scattered logic.</li><li>We’ll contrast this with a flatter Go structure later.</li></ul></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
