// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960

package slides

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

/*
Slide: 2024 - How did it go?

Intent:
- Story beat + foreshadowing: we underestimated, crunched, shipped not-prod-ready, but made it usable.
- Keep the slide readable. Save the technical blame/analysis for later comparison slides.

Notes:
- We will revisit two major design mistakes later:
  1) Overusing Server Components (wrong fit in several places).
  2) Firebase is excellent when used correctly, but our usage (and mixing patterns with Server Components)
     contributed to poor performance, including in the core interest-selection flow.
*/

func Build2024HowDidItGo(isPresenter bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"slide\"><h1>How did it go in 2024?</h1><ul><li>We underestimated the work (by a lot)</li><li>We shipped <strong>not production-ready</strong></li><li>Crunch happened — even coding during the festival</li><li>But it was usable in the end</li></ul></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isPresenter {
			templ_7745c5c3_Err = build2024HowDidItGoPresenterNotes().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

func build2024HowDidItGoPresenterNotes() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"presenter-notes\"><ul><li>We’re real developers, so of course we grossly underestimated how much work was involved.</li><li>We didn’t complete all the features and the website was definitely not production ready.</li><li>With a lot of crunch — and some wild coding during the festival — it was usable in the end.</li><li>We decided we would not make that mistake again… (foreshadowing).</li></ul><div style=\"margin-top: 1rem;\">We’ll come back to two major design mistakes later in the talk:</div><ul><li>We tried to use Server Components everywhere, even when it was the wrong fit.</li><li>Firebase is amazing and very performant when implemented correctly, but our usage (and mixing patterns with Server Components) resulted in poor performance, including in the core interest selection flow.</li></ul></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
