// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package slides

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

/*
Slide: 2024 philosophy (why this stack)

Intent:
- Explain the real motivation for the 2024 choices.
- Not “batteries included” or “move fast” — this was about learning and realtime.

On-slide:
- We chose Next.js to learn it (already use React at work), especially Server Components.
- We chose Firestore because we’d used it before and wanted realtime features.
- Goal: make the site feel modern and alive.
*/

func Build2024Philosophy(isPresenter bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"slide\"><h1>2024: Why Next.js + Firebase</h1><ul><li>We wanted to learn Next.js (we already use React at work)</li><li>Especially: <strong>Server Components</strong></li><li>We chose Firestore for <strong>realtime</strong> features</li><li>Goal: make the site feel <strong>modern and alive</strong></li></ul></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isPresenter {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"presenter-notes\">This wasn’t a “pick the simplest thing” year. This was a learning year. We already knew React, but Next.js has its own mental model — we wanted to understand it properly. And Firebase: we’d used it before, and realtime is genuinely cool when it fits.</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
