// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package slides

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

/*
Slide: Different viewpoints

Intent:
- Signal diversity of opinions inside the team.
- Make space for the audience to disagree without conflict.
- Light humor, not hostile.

Design:
- Two big quotes.
- Optional: a simple spectrum line via inline CSS.
*/

func DifferentViewpoints(isPresenter bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"slide\"><h1>Different viewpoints</h1><div style=\"display:grid; grid-template-columns: 1fr 1fr; gap: 4rem; margin-top: 2rem;\"><div style=\"font-size: 1.6rem;\">“I can’t see the value of heavy frontend frameworks. Anything React can do, simple HTML, CSS, Go, Datastar can do better and with less complexity.<br><strong>Prove me wrong.</strong>”</div><div style=\"font-size: 1.6rem;\">“I’m trying to decide where to get my<br><strong>VS Code + React</strong> tattoos.”</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isPresenter {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"presenter-notes\"><ul><li>We disagree internally — and that's ok</li><li>While working on this presentation I relized  we have very different opinions, and that's a strength.</li><li>Personally I am biased towards less complexity, Html, Css, Go, Datastar</li><li>You will hear differnt viewpoints. Things some consider good, others consider bad.</li></ul></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
