// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package slides

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

/*
Slide: Structure

Intent:
- Show that structure is a tradeoff in both approaches.
- Next.js file-based routing is discoverable, but can explode into deep nesting + page.tsx everywhere.
- Go is less opinionated about folders, which enables feature-based structure and high locality,
  but routing can get messy quickly if not kept disciplined.
- End with the shared goal: locality + cohesion are achievable in both.

On-slide bullets (Good/Bad only, short and punchy):
- Group into Next.js vs Go to keep it readable.
*/

func StructureGoodBad(isPresenter bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"slide\"><h1>Structure</h1><div style=\"display:flex; flex-direction:column; gap:1.5rem; margin-top:2rem;\"><div><div style=\"font-weight:800; font-size:1.3rem; margin-bottom:0.75rem;\">Next.js</div><ul style=\"margin:0;\"><li><strong>Good:</strong> Folder routing is super discoverable</li><li><strong>Bad:</strong> Folder routing ⇒ <strong>page.tsx</strong> everywhere</li><li><strong>Bad:</strong> Too many folders (deep nesting)</li></ul></div><div><div style=\"font-weight:800; font-size:1.3rem; margin-bottom:0.75rem;\">Go</div><ul style=\"margin:0;\"><li><strong>Good:</strong> Not opinionated about folders — structure by <strong>feature</strong>, not framework rules</li><li><strong>Bad:</strong> Routers can get messy quick</li></ul></div><div><ul style=\"margin:0;\"><li><strong>Good:</strong> You can achieve high locality and cohesion in both Next.js and Go</li></ul></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isPresenter {
			templ_7745c5c3_Err = structureGoodBadPresenterNotes().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

func structureGoodBadPresenterNotes() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"presenter-notes\"><ul><li>This slide is not “Next bad / Go good” — it’s about tradeoffs.</li><li>Next.js helps you find routes fast, but it can push features to spread across many folders.</li><li>Go gives you freedom: feature folders can keep templates, SQL, handlers, and related code together.</li><li>The risk with Go is letting routing become a dumping ground. Keep route logic close to the feature.</li></ul></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
