// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package slides

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

/*
Slide: Why this software exists (project north star)

Intent:
- Explain why this is more than “a calendar”.
- Give one guiding vision statement that anchors UX decisions.
- Set up the “real production” constraint + foreshadowing.

Design:
- One strong vision statement (NO wall of text).
- Optionally show Norwegian + English translation.
*/

func ProjectVision(isPresenter bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"slide\"><h1>Why this software exists</h1><div style=\"font-size: 1.8rem; margin-top: 2rem; line-height: 1.3;\"><strong>\"Vi gjør vårt beste for at alle deltagere skal få spille minst et spill som de er veldig interessert i.\"</strong></div><div style=\"font-size: 1.6rem; margin-top: 1rem; font-style: italic; \">\"We do our best to ensure every participant gets to play at least one game they’re really excited to play.\"</div><ul style=\"margin-top: 2rem;\"><li>The deves take the oppertunity to learn new things and try other thecnology's than we use at work.</li></ul><ul style=\"margin-top: 2rem;\"><li>This is a real production system, used by real people. <i>(forshadowing)</i></li></ul></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isPresenter {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"presenter-notes\"><ul><li>This vision drives UX and prioritization.</li><li>This is why a simple calendar plugin doesn’t fit.</li><li>Foreshadowing</li></ul></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
