// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import ()

func emojiBalloonScript() string {
	return `
<script type="module">
  class EmojiBalloon extends HTMLElement {
    constructor() {
      super();
      this._storageKey = null;
      this._cleanupTimer = null;
      this._hasConnected = false;
      this._activeAnimation = null;
    }

    connectedCallback() {
      this._hasConnected = true;
      this._runCheck("connectedCallback");
    }

    static get observedAttributes() {
      return ["data-emoji", "data-count"];
    }

    attributeChangedCallback(name, oldValue, newValue) {
      if (!this.isConnected) return;
      if (!this._hasConnected) return;

      if (oldValue === newValue) return;
      this._runCheck("attributeChangedCallback: " + name);
    }

    _runCheck(source) {
      const emoji = (this.getAttribute("data-emoji") || "").trim();
      const countStrRaw = this.getAttribute("data-count") || "0";
      const countStr = countStrRaw.trim();
      const count = Number(countStr);

      this._storageKey = "fmj26:emojiCount:" + encodeURIComponent(emoji);

      const storedRaw = sessionStorage.getItem(this._storageKey);
      const stored = storedRaw === null ? null : Number(storedRaw);

      if (!Number.isFinite(count)) {
        console.warn("[emoji-balloon] count is not a number:", countStrRaw);
        return;
      }

      if (storedRaw === null) {
        sessionStorage.setItem(this._storageKey, String(count));
        return;
      }

      if (Number.isFinite(stored) && count > stored) {
        this._animate();
      }

      sessionStorage.setItem(this._storageKey, String(count));
    }

    _animate() {
      const target = this.querySelector("[data-emoji-balloon-target]");
      if (!target) return;

      // Cancel any in-flight animation so repeated clicks feel snappy.
      if (this._activeAnimation) {
        this._activeAnimation.cancel();
        this._activeAnimation = null;
      }

      // Cute balloon pop: up + slight overshoot.
      this._activeAnimation = target.animate(
        [
          { transform: "translateY(0px) scale(1)" },
          { transform: "translateY(-12px) scale(1.14)", offset: 0.45 },
          { transform: "translateY(-18px) scale(1.02)" },
        ],
        {
          duration: 320,
          easing: "cubic-bezier(0.2, 0.9, 0.2, 1)",
          fill: "none",
        }
      );
    }
  }

  if (!customElements.get("emoji-balloon")) {
    customElements.define("emoji-balloon", EmojiBalloon);
  }
</script>

<style>
  @keyframes emojiBalloonPop {
    0%   { transform: translateY(0) scale(1); }
    45%  { transform: translateY(-10px) scale(1.14); }
    100% { transform: translateY(-16px) scale(1.02); }
  }

  .emoji-balloon-pop {
    display: inline-block;
    animation: emojiBalloonPop 320ms cubic-bezier(0.2, 0.9, 0.2, 1);
    will-change: transform;
  }
</style>
`
}

func EmojiBalloonAssets() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(emojiBalloonScript()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
