// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"log/slog"
	"net/http"
	"os"
	"path"
	"strings"

	"github.com/Regncon/frontiers-meetup-january-2026/components"
	"github.com/go-chi/chi/v5"
	"github.com/gorilla/sessions"
)

const presenterSessionName = "presenter-auth"

func PresenterRoutes(router chi.Router, store sessions.Store, logger *slog.Logger) {
	router.Route("/presenter", func(presenterRouter chi.Router) {
		presenterRouter.Get("/", func(w http.ResponseWriter, r *http.Request) {
			ctx := r.Context()

			isPresenter, err := getPresenterFlag(r, store)
			if err != nil {
				logger.Error("failed to read presenter session", slog.String("error", err.Error()))
				http.Redirect(w, r, "../", http.StatusFound)
				return
			}

			flash, err := popPresenterFlash(r, w, store)
			if err != nil {
				logger.Error("failed to read presenter flash", slog.String("error", err.Error()))
				flash = ""
			}

			components.BaseLayout(
				"Presenter mode",
				PresenterPage(isPresenter, flash),
			).Render(ctx, w)
		})

		presenterRouter.Post("/login", func(w http.ResponseWriter, r *http.Request) {
			if err := r.ParseForm(); err != nil {
				_ = setPresenterFlash(w, r, store, "Invalid form submission.")
				redirectToPresenterHome(w, r)
				return
			}

			entered := strings.TrimSpace(r.FormValue("key"))
			expected := strings.TrimSpace(os.Getenv("PRESENTER_KEY"))

			if entered == "" || expected == "" || entered != expected {
				_ = setPresenterFlash(w, r, store, "Invalid presenter key.")
				redirectToPresenterHome(w, r)
				return
			}

			if err := setPresenterFlag(w, r, store, true); err != nil {
				logger.Error("failed to set presenter session", slog.String("error", err.Error()))
				_ = setPresenterFlash(w, r, store, "Failed to enable presenter mode.")
				redirectToPresenterHome(w, r)
				return
			}

			redirectToPresenterHome(w, r)
		})

		presenterRouter.Post("/logout", func(w http.ResponseWriter, r *http.Request) {
			if err := setPresenterFlag(w, r, store, false); err != nil {
				logger.Error("failed to clear presenter session", slog.String("error", err.Error()))
				_ = setPresenterFlash(w, r, store, "Failed to log out.")
				redirectToPresenterHome(w, r)
				return
			}

			redirectToPresenterHome(w, r)
		})
	})
}

func redirectToPresenterHome(w http.ResponseWriter, r *http.Request) {
	// When mounted under a secret prefix, r.URL.Path looks like:
	// /a_super_secret_key_12345/presenter/login
	// We want:
	// /a_super_secret_key_12345/presenter
	//
	// path.Dir => /a_super_secret_key_12345/presenter
	http.Redirect(w, r, path.Dir(r.URL.Path), http.StatusSeeOther) // 303
}

func getPresenterFlag(r *http.Request, store sessions.Store) (bool, error) {
	sess, err := store.Get(r, presenterSessionName)
	if err != nil {
		return false, err
	}

	v, ok := sess.Values["presenter"].(bool)
	return ok && v, nil
}

func setPresenterFlag(w http.ResponseWriter, r *http.Request, store sessions.Store, isPresenter bool) error {
	sess, err := store.Get(r, presenterSessionName)
	if err != nil {
		return err
	}

	sess.Values["presenter"] = isPresenter
	return sess.Save(r, w)
}

func setPresenterFlash(w http.ResponseWriter, r *http.Request, store sessions.Store, message string) error {
	sess, err := store.Get(r, presenterSessionName)
	if err != nil {
		return err
	}

	sess.Values["flash"] = message
	return sess.Save(r, w)
}

func popPresenterFlash(r *http.Request, w http.ResponseWriter, store sessions.Store) (string, error) {
	sess, err := store.Get(r, presenterSessionName)
	if err != nil {
		return "", err
	}

	msg, _ := sess.Values["flash"].(string)
	if msg == "" {
		return "", nil
	}

	delete(sess.Values, "flash")
	if err := sess.Save(r, w); err != nil {
		return "", err
	}

	return msg, nil
}

func PresenterPage(isPresenter bool, errorMessage string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div style=\"max-width: 42rem; margin: 4rem auto; padding: 0 1rem;\"><h1 style=\"font-size: 2rem; margin-bottom: 0.75rem;\">Presenter mode</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if errorMessage != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div style=\"padding: 0.75rem 1rem; border-radius: 12px; border: 1px solid rgba(255,0,0,0.35); margin-bottom: 1rem;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(errorMessage)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/presenter.templ`, Line: 144, Col: 18}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if !isPresenter {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<p style=\"opacity: 0.85; margin-bottom: 1rem;\">Enter the presenter key to enable presenter controls on this device.</p><form method=\"post\" action=\"/presenter/login\" style=\"display:flex; gap:0.5rem; align-items:center; flex-wrap:wrap;\"><input type=\"password\" name=\"key\" placeholder=\"Presenter key\" autocomplete=\"current-password\" style=\"flex:1; min-width: 16rem; padding: 0.65rem 0.75rem; border-radius: 10px;\"> <button type=\"submit\" style=\"padding: 0.65rem 0.9rem; border-radius: 10px;\">Unlock</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<p style=\"opacity: 0.85; margin-bottom: 1rem;\">This device is currently in presenter mode.</p><form method=\"post\" action=\"/presenter/logout\"><button type=\"submit\" style=\"padding: 0.65rem 0.9rem; border-radius: 10px;\">Log out presenter mode</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
