// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package root

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"database/sql"
	"fmt"

	"github.com/Regncon/frontiers-meetup-january-2026/slides"
)

type slideFunc func() templ.Component

func deck(
	db *sql.DB,
	inviteKey string,
	sessionID string,
	isPresenter bool,
	localKey string,
	remoteKey string,
) []slideFunc {
	poll := MustPoll("dom-checkbox-limit")
	pollConcurrency := MustPoll("regncon-concurrency")

	return []slideFunc{
		func() templ.Component { return slides.LobbyWelcome(isPresenter) },
		func() templ.Component { return slides.WhyThisTalk(isPresenter) },

		func() templ.Component { return slides.Agenda(slides.AgendaWhoWeAre, isPresenter) },
		func() templ.Component { return slides.WhatIsRegncon(isPresenter) },
		func() templ.Component { return slides.ProjectVision(isPresenter) },
		func() templ.Component { return slides.WhoWeAre(isPresenter) },
		func() templ.Component { return slides.DifferentViewpoints(isPresenter) },

		func() templ.Component { return slides.Agenda(slides.Agenda2024, isPresenter) },
		func() templ.Component { return slides.Build2024Philosophy(isPresenter) },
		//func() templ.Component { return slides.WhatIsNextJS(isPresenter) },
		//func() templ.Component { return slides.WhatIsFirebase(isPresenter) },
		func() templ.Component { return slides.Build2024Snapshot(isPresenter) },
		func() templ.Component { return slides.Build2024HowDidItGo(isPresenter) },

		func() templ.Component { return slides.Agenda(slides.Agenda2025, isPresenter) },
		func() templ.Component { return slides.Build2025Philosophy(isPresenter) },
		func() templ.Component { return slides.GrugBrainMeme(isPresenter) },
		func() templ.Component { return slides.Build2025HowWeChoseTheStack(isPresenter) },
		//func() templ.Component { return slides.WhatIsGo(isPresenter) },
		func() templ.Component { return slides.WhatIsTempl(isPresenter) },

		func() templ.Component { return slides.WhatIsDatastar(isPresenter) },
		func() templ.Component { return slides.DatastarCheckboxTrickSetup(isPresenter) },
		func() templ.Component { return PollSlide(db, inviteKey, sessionID, poll) },
		func() templ.Component { return PollResultsSlide(db, poll, localKey, remoteKey) },
		func() templ.Component { return slides.DatastarCheckboxTrickReveal(isPresenter) },
		func() templ.Component { return slides.DatastarCheckboxTrickDemo(isPresenter) },
		//func() templ.Component { return slides.WhatIsSQLite(isPresenter) },
		//func() templ.Component { return slides.WhatIsNATS(isPresenter) },
		func() templ.Component { return slides.Build2025Snapshot(isPresenter) },
		func() templ.Component { return slides.Build2025HowDidItGoQuestion(isPresenter) },
		func() templ.Component { return slides.Build2025ServerExplosion(isPresenter) },
		func() templ.Component { return slides.Build2025HowDidItGo(isPresenter) },

		func() templ.Component { return slides.Agenda(slides.AgendaCompare, isPresenter) },
		func() templ.Component { return slides.Stack2024GoodBad(isPresenter) },
		func() templ.Component { return slides.Stack2025GoodBad(isPresenter) },

		func() templ.Component { return slides.RegnconConcurrencyPollSetup(isPresenter) },
		func() templ.Component { return PollSlide(db, inviteKey, sessionID, pollConcurrency) },
		func() templ.Component { return PollResultsSlide(db, pollConcurrency, localKey, remoteKey) },
		func() templ.Component { return slides.RegnconConcurrencyPollReveal(isPresenter) },

		func() templ.Component { return slides.ComplexityEssentialVsAccidental(isPresenter) },

		func() templ.Component { return slides.StylingGoodBad(isPresenter) },
		func() templ.Component { return slides.ToolingAndDXGoodBad(isPresenter) },
		func() templ.Component { return slides.LLMAssistanceGoodBad(isPresenter) },
		func() templ.Component { return slides.Agenda(slides.AgendaTakeaways, isPresenter) },
	}
}

func deckSize() int {
	// Only used for clamping; closures won't be executed.
	return len(deck(nil, "", "", true, "", ""))
}

func clampSlideIndex(index int) int {
	if index < 0 {
		return 0
	}

	size := deckSize()
	if size == 0 {
		return 0
	}

	if index >= size {
		return size - 1
	}

	return index
}

func slideAt(deck []slideFunc, index int) slideFunc {
	if index < 0 || index >= len(deck) {
		return func() templ.Component { return UnknownSlide() }
	}
	return deck[index]
}

// --- Components ---
func ActiveSlide(
	db *sql.DB,
	inviteKey string,
	sessionID string,
	isPresenter bool,
	localKey string,
	remoteKey string,
) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		index, _ := GetCurrentSlideIndex(db)
		deckLocal := deck(db, inviteKey, sessionID, isPresenter, localKey, remoteKey)
		index = clampSlideIndex(index)
		slideComponent := slideAt(deckLocal, index)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div data-signals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("{ slideIndex: %d }", index))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/root/active_slide.templ`, Line: 120, Col: 61}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = slideComponent().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func UnknownSlide() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<p>Unknown slide</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
