// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package root

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"database/sql"
	"fmt"

	"github.com/Regncon/frontiers-meetup-january-2026/slides"
)

type slideEntry struct {
	Title  string
	Render func() templ.Component
}

func deck(
	db *sql.DB,
	inviteKey string,
	sessionID string,
	isPresenter bool,
	localKey string,
	remoteKey string,
) []slideEntry {
	poll := MustPoll("dom-checkbox-limit")
	pollConcurrency := MustPoll("regncon-concurrency")

	return []slideEntry{
		{Title: "Lobby welcome", Render: func() templ.Component { return slides.LobbyWelcome(isPresenter) }},
		{Title: "Why this talk", Render: func() templ.Component { return slides.WhyThisTalk(isPresenter) }},

		{Title: "Agenda: Who we are", Render: func() templ.Component { return slides.Agenda(slides.AgendaWhoWeAre, isPresenter) }},
		{Title: "What is Regncon?", Render: func() templ.Component { return slides.WhatIsRegncon(isPresenter) }},
		{Title: "Why this software exists", Render: func() templ.Component { return slides.ProjectVision(isPresenter) }},
		{Title: "Who we are", Render: func() templ.Component { return slides.WhoWeAre(isPresenter) }},
		{Title: "Different viewpoints", Render: func() templ.Component { return slides.DifferentViewpoints(isPresenter) }},

		{Title: "Agenda: 2024", Render: func() templ.Component { return slides.Agenda(slides.Agenda2024, isPresenter) }},
		{Title: "2024: Why Next.js + Firebase", Render: func() templ.Component { return slides.Build2024Philosophy(isPresenter) }},
		//{Title: "What is Next.js?", Render: func() templ.Component { return slides.WhatIsNextJS(isPresenter) }},
		//{Title: "What is Firebase?", Render: func() templ.Component { return slides.WhatIsFirebase(isPresenter) }},
		{Title: "What we built in 2024", Render: func() templ.Component { return slides.Build2024Snapshot(isPresenter) }},
		{Title: "How did it go in 2024?", Render: func() templ.Component { return slides.Build2024HowDidItGo(isPresenter) }},

		{Title: "Agenda: 2025", Render: func() templ.Component { return slides.Agenda(slides.Agenda2025, isPresenter) }},
		{Title: "2025: The opposite experiment", Render: func() templ.Component { return slides.Build2025Philosophy(isPresenter) }},
		{Title: "Grug brain developer?", Render: func() templ.Component { return slides.GrugBrainMeme(isPresenter) }},
		{Title: "How we chose the stack (2025)", Render: func() templ.Component { return slides.Build2025HowWeChoseTheStack(isPresenter) }},
		//{Title: "What is Go?", Render: func() templ.Component { return slides.WhatIsGo(isPresenter) }},
		{Title: "What is templ?", Render: func() templ.Component { return slides.WhatIsTempl(isPresenter) }},

		{Title: "What is Datastar?", Render: func() templ.Component { return slides.WhatIsDatastar(isPresenter) }},
		{Title: "Datastar demo", Render: func() templ.Component { return slides.DatastarCheckboxTrickSetup(isPresenter) }},
		{Title: "Poll: " + poll.QuestionText, Render: func() templ.Component { return PollSlide(db, inviteKey, sessionID, poll) }},
		{Title: "Results: " + poll.QuestionText, Render: func() templ.Component { return PollResultsSlide(db, poll, localKey, remoteKey) }},
		{Title: "Datastar demo (reveal)", Render: func() templ.Component { return slides.DatastarCheckboxTrickReveal(isPresenter) }},
		{Title: "Datastar demo (live)", Render: func() templ.Component { return slides.DatastarCheckboxTrickDemo(isPresenter) }},
		//{Title: "What is SQLite?", Render: func() templ.Component { return slides.WhatIsSQLite(isPresenter) }},
		//{Title: "What is NATS?", Render: func() templ.Component { return slides.WhatIsNATS(isPresenter) }},
		{Title: "What we built in 2025", Render: func() templ.Component { return slides.Build2025Snapshot(isPresenter) }},
		{Title: "How did it go in 2025? (question)", Render: func() templ.Component { return slides.Build2025HowDidItGoQuestion(isPresenter) }},
		{Title: "2025 server explosion", Render: func() templ.Component { return slides.Build2025ServerExplosion(isPresenter) }},
		{Title: "How did it go in 2025?", Render: func() templ.Component { return slides.Build2025HowDidItGo(isPresenter) }},

		{Title: "Agenda: Compare", Render: func() templ.Component { return slides.Agenda(slides.AgendaCompare, isPresenter) }},
		{Title: "Stack (2024)", Render: func() templ.Component { return slides.Stack2024GoodBad(isPresenter) }},
		{Title: "Next.js CVE impact", Render: func() templ.Component { return slides.NextJSCVE202555182Impact(isPresenter) }},
		{Title: "Stack (2025)", Render: func() templ.Component { return slides.Stack2025GoodBad(isPresenter) }},

		{Title: "Scaling", Render: func() templ.Component { return slides.RegnconConcurrencyPollSetup(isPresenter) }},
		{Title: "Poll: " + pollConcurrency.QuestionText, Render: func() templ.Component { return PollSlide(db, inviteKey, sessionID, pollConcurrency) }},
		{Title: "Results: " + pollConcurrency.QuestionText, Render: func() templ.Component { return PollResultsSlide(db, pollConcurrency, localKey, remoteKey) }},
		{Title: "Scaling (reveal)", Render: func() templ.Component { return slides.RegnconConcurrencyPollReveal(isPresenter) }},

		{Title: "Language: Go (KO)", Render: func() templ.Component { return slides.LanguageGoKOSlide(isPresenter) }},
		{Title: "Language: Go", Render: func() templ.Component { return slides.LanguageGoWins(isPresenter) }},
		{Title: "Go is not perfect", Render: func() templ.Component { return slides.LanguageGoNotPerfect(isPresenter) }},
		{Title: "Error handling", Render: func() templ.Component { return slides.LanguageGoErrorHandling(isPresenter) }},
		{Title: "JS/TS wins", Render: func() templ.Component { return slides.LanguageJSTSWins(isPresenter) }},
		{Title: "Complexity", Render: func() templ.Component { return slides.ComplexityEssentialVsAccidental(isPresenter) }},

		{Title: "Structure", Render: func() templ.Component { return slides.StructureGoodBad(isPresenter) }},
		{Title: "Next.Js src tree", Render: func() templ.Component { return slides.NextJSSrcTree(isPresenter) }},

		{Title: "Tooling / DX (KO)", Render: func() templ.Component { return slides.ToolingDXKOSlide(isPresenter) }},
		{Title: "Tooling / DX", Render: func() templ.Component { return slides.ToolingAndDXGoodBad(isPresenter) }},
		{Title: "Styling", Render: func() templ.Component { return slides.StylingGoodBad(isPresenter) }},
		{Title: "LLM assistance", Render: func() templ.Component { return slides.LLMAssistanceGoodBad(isPresenter) }},
		{Title: "Agenda: What's next", Render: func() templ.Component { return slides.Agenda(slides.AgendaWhatsNext, isPresenter) }},
		{Title: "What's next?", Render: func() templ.Component { return slides.WhatsNext2026_2027(isPresenter) }},
		{Title: "Agenda: QnA", Render: func() templ.Component { return slides.Agenda(slides.Discussion, isPresenter) }},
	}
}

func deckSize() int {
	// Only used for clamping; closures won't be executed.
	return len(deck(nil, "", "", true, "", ""))
}

func clampSlideIndex(index int) int {
	if index < 0 {
		return 0
	}

	size := deckSize()
	if size == 0 {
		return 0
	}

	if index >= size {
		return size - 1
	}

	return index
}

func slideEntryAt(deck []slideEntry, index int) slideEntry {
	if index < 0 || index >= len(deck) {
		return slideEntry{
			Title:  "Unknown slide",
			Render: func() templ.Component { return UnknownSlide() },
		}
	}
	return deck[index]
}

// --- Components ---
func ActiveSlide(
	db *sql.DB,
	inviteKey string,
	sessionID string,
	isPresenter bool,
	localKey string,
	remoteKey string,
) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		index, _ := GetCurrentSlideIndex(db)
		deckLocal := deck(db, inviteKey, sessionID, isPresenter, localKey, remoteKey)
		index = clampSlideIndex(index)
		slideComponent := slideEntryAt(deckLocal, index)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div data-signals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("{ slideIndex: %d }", index))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/root/active_slide.templ`, Line: 138, Col: 61}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = slideComponent.Render().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func UnknownSlide() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<p>Unknown slide</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
