// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package root

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"

	"encoding/json"
	"github.com/Regncon/frontiers-meetup-january-2026/services"
	"github.com/delaneyj/toolbelt/embeddednats"
	"github.com/starfederation/datastar-go/datastar"
)

func IncrementEmojiRoute(router chi.Router, ns *embeddednats.Server) {
	ebs, _ := services.NewEmojiBalloonService(ns)

	router.Get("/emoji/sse", func(w http.ResponseWriter, r *http.Request) {

		sse := datastar.NewSSE(w, r)
		ctx := r.Context()

		watcher, err := ebs.WatchUpdates(ctx)
		if err != nil {
			http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		}

		fmt.Println(ebs.Counter)
		thumbs_up := ebs.Counter.ThumbsUpEmojiCount
		confetti := ebs.Counter.ConfettiEmojiCount
		cry_laugh := ebs.Counter.CryLaughEmojiCount
		fire := ebs.Counter.FireEmojiCount
		heart := ebs.Counter.HeartEmojiCount

		for {
			select {
			case <-ctx.Done():
				return
			case <-watcher.Updates():

				b, err := json.Marshal(ebs.Counter)

				if err != nil {
					http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
				}

				err = sse.PatchSignals(b)

				if err != nil {
					http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
				}

				emoji := ""

				if thumbs_up != ebs.Counter.ThumbsUpEmojiCount {
					thumbs_up = ebs.Counter.ThumbsUpEmojiCount
					emoji = "👍"
				}
				if confetti != ebs.Counter.ConfettiEmojiCount {
					confetti = ebs.Counter.ConfettiEmojiCount
					emoji = "🎉"
				}
				if cry_laugh != ebs.Counter.CryLaughEmojiCount {
					cry_laugh = ebs.Counter.CryLaughEmojiCount
					emoji = "😂"
				}
				if fire != ebs.Counter.FireEmojiCount {
					fire = ebs.Counter.FireEmojiCount
					emoji = "🔥"
				}
				if heart != ebs.Counter.HeartEmojiCount {
					heart = ebs.Counter.HeartEmojiCount
					emoji = "❤️"
				}

				err = sse.PatchElements(fmt.Sprintf(`<emoji-balloon emoji="%s"></emoji-balloon>`, emoji), datastar.WithSelector("body"), datastar.WithModeAppend())
				if err != nil {
					http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
				}
			}
		}
	})

	router.Post("/emoji/increment", func(w http.ResponseWriter, r *http.Request) {
		type Signals struct {
			Emoji string
		}
		var signals Signals
		err := datastar.ReadSignals(r, &signals)
		if err != nil {
			http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		}

		err = ebs.AddBalloon(r.Context(), signals.Emoji)
		if err != nil {
			http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		}
	})
}

func emojiIncrementPostURL(inviteKey string) string {
	return fmt.Sprintf("@post('/%s/root/api/emoji/increment')", inviteKey)
}

func emojiVoteSSEGetURL(inviteKey string) string {
	return fmt.Sprintf("@get('/%s/root/api/emoji/sse',{requestCancellation: 'disabled'})", inviteKey)
}

func EmojiVoteWidget(inviteKey string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"absolute bottom-0 left-0 p-4 w-full flex gap-4 justify-center items-center\" data-init=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(emojiVoteSSEGetURL(inviteKey))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/root/emoji_counter.templ`, Line: 111, Col: 43}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-on:click__stop=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(emojiIncrementPostURL(inviteKey))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/root/emoji_counter.templ`, Line: 112, Col: 56}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"><button class=\"emoji-balloon-button\" data-on:click=\"$emoji='👍';\"><span data-text=\"$ThumbsUpEmojiCount\"></span> 👍</button> <button class=\"emoji-balloon-button\" data-on:click=\"$emoji='🎉';\"><span data-text=\"$ConfettiUpEmojiCount\"></span> 🎉</button> <button class=\"emoji-balloon-button\" data-on:click=\"$emoji='😂';\"><span data-text=\"$CryLaughEmojiCount\"></span> 😂</button> <button class=\"emoji-balloon-button\" data-on:click=\"$emoji='🔥';\"><span data-text=\"$FireEmojiCount\"></span> 🔥</button> <button class=\"emoji-balloon-button\" data-on:click=\"$emoji='❤️';\"><span data-text=\"$HeartEmojiCount\"></span> ❤️</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
